SELECT 5+11;
SELECT now();
SELECT ucase('PratiBha YaDav');

SELECT WORKER_ID, Department FROM Worker ;

SELECT * FROM Worker WHERE SALARY>600000;
SELECT * FROM Worker WHERE DEPARTMENT='HR';
SELECT FIRST_NAME FROM Worker WHERE SALARY>400000;

SELECT FIRST_NAME FROM Worker WHERE SALARY BETWEEN 30000 AND 50000;

SELECT * FROM Worker WHERE FIRST_NAME IN ('Walter', 'Harry');

SELECT * FROM Worker WHERE FIRST_NAME='Daenerys' OR FIRST_NAME='Zendaya';

SELECT FIRST_NAME, DEPARTMENT FROM Worker WHERE DEPARTMENT NOT IN('HR');

-- WILDCARD
SELECT * FROM Worker WHERE LAST_NAME LIKE '%H%';
SELECT * FROM Worker WHERE LAST_NAME LIKE '%A%';

-- SORTING
SELECT * FROM Worker ORDER BY SALARY;
SELECT * FROM Bonus ORDER BY BONUS_AMOUNT DESC;

-- DISTINCT VALUES
SELECT DISTINCT DEPARTMENT FROM Worker;
SELECT DISTINCT WORKER_TITLE FROM Title;

-- GROUP BY
SELECT DEPARTMENT FROM Worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT, COUNT(*) FROM Worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM Worker GROUP BY DEPARTMENT;

-- AVERAGE SALARY BY DEPARTMENT
SELECT DEPARTMENT, AVG(SALARY) FROM Worker GROUP BY DEPARTMENT;

-- MINIMUM SALARY BY DEPARTMENT
SELECT DEPARTMENT, MIN(SALARY) FROM Worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MIN(WORKER_ID) FROM Worker GROUP BY DEPARTMENT;

-- MAX SALARY BY DEPARTEMNY
SELECT DEPARTMENT, MAX(SALARY) FROM Worker GROUP BY DEPARTMENT;

-- SUM SALARY BY DEPARTMENT
SELECT DEPARTMENT, SUM(SALARY) FROM Worker GROUP BY DEPARTMENT;

-- GROUP BY CONDITION HAVING
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM Worker GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)>2;
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM Worker GROUP BY DEPARTMENT HAVING SUM(SALARY)>20000;


